name: Download Daily Wallpaper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
   
      - name: Download Unsplash daily image
        run: |
          npm i -g unsplash-js
          cd ./assets/
          node -e "const { toJson } = require('unsplash-js'); const fetch = require('node-fetch'); const Unsplash = require('unsplash-js').default; const unsplash = new Unsplash({ accessKey: '${{ secrets.UNSPLASH_ACCESS_KEY }}' }); unsplash.photos.getRandomPhoto({ featured: true }).then(toJson).then(json => { fetch(json.urls.full).then(response => { const dest = fs.createWriteStream('unsplash_wallpaper.jpg'); response.body.pipe(dest); }); });"
          
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: 'Download Daily Wallpaper'
